---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gw
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: web-gw
    allowedRoutes:
      namespaces:
        from: kafka
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kafka-ui
spec:
  parentRefs:
  - name: public-gw
    namespace: kafka
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /healthcheck
    backendRefs:
    - name: healthcheck-global
      port: 80
