apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public
  namespace: metallb-system
spec:
  addresses:
  - 10.10.141.50/27

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-l2-advertisement
  namespace: metallb-system
