apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: sensit-pod-policy
  namespace: sensit-stuff
spec:
  endpointSelector:
    matchLabels:
      privacyLevel: "sensit"
  egress:
    - {}
