apiVersion: v1
kind: Service
metadata:
  name: docs
spec:
  selector:
    app: docs # This must match the 'app' label of your Deployment's Pods
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the Service
      targetPort: 8080  # Port on the Pod where the application listens
  type: ClusterIP # Or NodePort, LoadBalancer, ExternalName depending on your needs
