apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
type: Opaque
stringData:
  AUTH_SECRET: ${INFISICAL_AUTH_SECRET}
  ENCRYPTION_KEY: ${INFISICAL_ENC_KEY}
  SITE_URL: ${INFISICAL_SITE_URL}
  TELEMETRY_ENABLED: "false"
