---
apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: cilium-ipv4-config
  namespace: default
spec:
  description: "Gateway configuration for IPv4 LoadBalancer services"
  service:
    type: LoadBalancer
    ipFamilyPolicy: SingleStack
    ipFamilies:
    - IPv4
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium-ipv4
spec:
  controllerName: io.cilium/gateway-controller
  parametersRef:
    group: cilium.io
    kind: CiliumGatewayClassConfig
    name: cilium-ipv4-config
    namespace: default
